---
- hosts: all
  gather_facts: yes

  vars:
    ros_versions:
      trusty: indigo
      xenial: kinetic
      bionic: melodic
      focal: noetic

    wifi_tegra_ip_address: 192.168.1.10
    wifi_beagle_ip_address: 192.168.1.213
    ppp_tegra_ip_address: 192.168.5.100
    ppp_beagle_ip_address: 192.168.5.101

  roles:
    - role: soslab

    - role: moos
      when: target_type=="tegra"

    - role: ros
      ros_packages:
      - rviz
      when: target_type=="tegra"

    - role: sonar
      when: target_type=="tegra"

    - role: riptide_ros_bridge
      when: target_type=="tegra"

    - role: vnc
      when: target_type=="tegra"

    - role: ppp

    - role: udev
      when: target_type=="tegra"

    - role: chrony