---
# https://www.raspberrypi.org/forums/viewtopic.php?t=149927
- name: Install PPP packages
  apt:
    name:
    - dnsmasq
    - ppp
    - hostapd
  become: yes

- name: Create PPP confguration file
  ansible.builtin.template:
    src: ppp.options.j2
    dest: "/etc/ppp/options.{{ ppp_jetson_serial_interface }}"
  become: yes

- name: Create PPP systemd file
  ansible.builtin.template:
    src: ppp.service.j2
    dest: "/etc/systemd/system/ppp.service"
  become: yes

- name: Setup systemd ppp service
  ansible.builtin.systemd:
    name: ppp
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes