---
ppp_payload_ip_address: 192.168.2.10
ppp_tube_ip_address: 192.168.2.1
ppp_payload_serial_interface: ftdi
ppp_tube_serial_interface: ftdi

# Possible values are
# - 115200
# - 230400
# - 460800
# - 921600
ppp_baudrate: 921600