---
- name: Install chrony
  apt:
    name: chrony
  become: yes

- name: Copy config
  ansible.builtin.template:
    src: "chrony.{{ target_type }}.conf.j2"
    dest: /etc/chrony/chrony.conf
  become: yes

- name: Enable chrony
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: yes
  become: yes