---
- name: Install chrony
  apt:
    name: chrony
  become: yes

- name: Copy config
  ansible.builtin.template:
    src: "chrony.{{ target_type }}.conf.j2"
    dest: /etc/chrony/chrony.conf
  become: yes

- name: Enable chrony
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: yes
  become: yes

- name: Allow ntp requests
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 123
    jump: ACCEPT
  become: yes
  when: target_type=="nose"

- name: Allow ntp responses
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: udp
    destination_port: 123
    jump: ACCEPT
  become: yes
  when: target_type=="nose"

- name: Save ip tables
  ansible.builtin.shell: |
    sh -c "iptables-save > /etc/iptables.rules"
  become: yes
  when: target_type=="nose"