---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/swathRT
    state: directory
    mode: '0755'
  become: yes

- name: Copy swathRT configuration
  ansible.builtin.copy:
    src: RTsettings.ini
    dest: /etc/swathRT/RTsettings.ini
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Configure network
  ansible.builtin.copy:
    src: sonar_connection
    dest: /etc/NetworkManager/system-connections/sonar_connection
    mode: '0600'
  become: yes

- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:

- name: Copy systemd unit file
  ansible.builtin.copy:
    src: swath.service
    dest: /etc/systemd/system/swath.service
  become: yes

- name: Setup systemd service
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Setup systemd service
  ansible.builtin.systemd:
    name: swath
    enabled: yes
    state: started
  become: yes
