---
- name: Checkout The Code From Github Using Ansible.
  ansible.builtin.git:
    repo: 'https://{{ github_token }}@github.com/GSO-soslab/bathy_sonar_ros.git'
    dest: "{{ ansible_env.HOME }}/ros_ws/src/bathy_sonar_ros"

- name: Install required packages
  ansible.builtin.shell: |
    source /opt/ros/{{ ros_versions[ansible_lsb.codename] }}/setup.bash
    rosdep install --from-paths src --ignore-src --rosdistro={{ ros_versions[ansible_lsb.codename ] }} -y
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/ros_ws"

- name: Build ros packages
  ansible.builtin.shell: |
    source /opt/ros/{{ ros_versions[ansible_lsb.codename] }}/setup.bash
    catkin_make
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/ros_ws"


